[package]
name = "receipts-exec"
description = "Operators and lineage capture"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
receipts-core.workspace = true
receipts-plan.workspace = true

[dev-dependencies]
proptest.workspace = true

[lints]
workspace = true
